# Generated by Django 3.1.4 on 2021-01-05 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(code='nomatch', message='Password length has to be 8', regex='^.{8}$')])),
            ],
        ),
    ]
