# Generated by Django 3.1.4 on 2021-01-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=120)),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField()),
                ('host', models.EmailField(max_length=100)),
            ],
        ),
    ]
