# Generated by Django 3.1.4 on 2021-01-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_description',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
