# Generated by Django 3.1.4 on 2021-01-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='host',
            new_name='host_email',
        ),
        migrations.AddField(
            model_name='event',
            name='host_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
